//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
        public Nullable<int> UParticipantId { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Specializations Specializations { get; set; }
        public virtual UParticipants UParticipants { get; set; }
    }
}
